### ISSUE TITLE
死循环问题

### ISSUE THREAD

**Issue by ailon527** [Freedom-Mr/JavaFx-PaginationPicker-Release#2]
if (!middle) {
  if (this.currentPage <= (this.pageButtonCount + 1) / 2) {
    ...
  }
  else if (this.currentPage >= this.pageCount - (this.pageButtonCount + 1) / 2) {
    ...
    ...
    i = i == 1 ? this.pageCount - this.pageButtonCount : i;// 此处当页数与按钮数量一致时，将会进入死循环
  }
}

**Comment by ailon527** [comment]
修改建议：
int temp = this.pageCount - this.pageButtonCount;
i = i == 1 ? (temp==0?i:temp) : i;

**Comment by Freedom-Mr** [comment]
0.0.2版本已经修复
